sudo: required

dist: trusty

language: cpp

compiler: gcc

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt592-trusty
- sudo apt-get update  -qq
- sudo apt-get install -qq libsqlite3-dev libnetcdf-dev
- sudo apt-cache search qt59
- sudo apt-get install -qq qt59base qt59charts-no-lgpl qt59webengine qt59imageformats qt59connectivity qt59graphicaleffects qt59script qt59sensors qt59webchannel qt59svg qt59xmlpatterns qt59location qt59quickcontrols2 qt59quickcontrols 
- export PATH=/opt/qt59/bin:$PATH

script:
- uname -a
- which qmake
- gcc --version
- g++ --version
- . /opt/qt59/bin/qt59-env.sh
- /opt/qt59/bin/qmake MetOceanViewer.pro 
- make -j4
