sudo: required

dist: trusty

language: cpp

compiler: gcc

before_install:
- sudo add-apt-repository --yes ppa:beineri/opt-qt57-beta-trusty
- sudo apt-get update  -qq
- sudo apt-get install -qq libsqlite3-dev libnetcdf-dev
- sudo apt-cache search qt57
- sudo apt-get install -qq qt57base qt57charts-no-lgpl qt57webengine qt57imageformats qt57connectivity qt57graphicaleffects qt57script qt57sensors qt57webchannel qt57svg qt57xmlpatterns qt57location 
- export PATH=/opt/qt57/bin:$PATH

script:
- uname -a
- which qmake
- gcc --version
- g++ --version
- . /opt/qt57/bin/qt57-env.sh
- qmake MetOceanViewer.pro 
- make
